### ISSUE TITLE
issues with initialization

### ISSUE THREAD

**Issue by vstadnytskyi** [trautsned/thorlabs_kenesis_python#1]
Hi,

First of all, great job getting the DLL bound to Python, I have looked through your example for the LTS stage and I was able to get up to retrieving information out of the "device"

I can find the device, I get information about the device but I cannot move or get positon.

When I run 'device.Position' I get an error.
```

---------------------------------------------------------------------------
DeviceSettingsException                   Traceback (most recent call last)
Input In [48], in <module>
----> 1 device.Position

DeviceSettingsException: Device settings not initialized
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyMotorSettings(Int32 functionDepth)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.get_Position()


```

It seems I need to initialize it but I do not understand how and in your code you did not need to do that,

full code below.

```

#!/usr/bin/env python
# coding: utf-8

# ## Thorlabs Kinesis LTS150
# 
# following example https://github.com/trautsned/thorlabs_kenesis_python/blob/master/lts300_xyz_sweep.py

# In[1]:


import clr
clr.AddReference("System")

import sys
import time
import numpy as np
import matplotlib.pyplot as plt
import random  # only used for dummy data

from System import String
from System import Decimal
from System.Collections import *

# constants
sys.path.append(r"C:\Program Files\Thorlabs\Kinesis")
serial_number =serial= '45252134'

clr.AddReference("Thorlabs.MotionControl.Controls")
import Thorlabs.MotionControl.Controls

clr.AddReference("Thorlabs.MotionControl.DeviceManagerCLI")
clr.AddReference("Thorlabs.MotionControl.GenericMotorCLI")
clr.AddReference("Thorlabs.MotionControl.IntegratedStepperMotorsCLI")
from Thorlabs.MotionControl.DeviceManagerCLI import *
# from Thorlabs.MotionControl.GenericMotorCLI import *
from Thorlabs.MotionControl.IntegratedStepperMotorsCLI import *


def avg(a):
    return sum(a) / len(a)


def print_positions():
    print('position (x,y,z): ', device_x.Position, device_y.Position, device_z.Position)
    return


def initialize_device(serial):
    device = Thorlabs.MotionControl.IntegratedStepperMotorsCLI.LongTravelStage.CreateLongTravelStage(serial)
    device.Connect(serial)
    motorSettings = device.GetMotorConfiguration(serial)
    # print(motorSettings)
    deviceInfo = device.GetDeviceInfo()
    print(deviceInfo.Name, '  ', deviceInfo.SerialNumber)
    return device


# In[2]:


device_list_result = DeviceManagerCLI.BuildDeviceList()
print(device_list_result)


# In[3]:


serial_number =serial= '45252134'


# In[4]:


device = Thorlabs.MotionControl.IntegratedStepperMotorsCLI.LongTravelStage.CreateLongTravelStage(serial)


# In[5]:


device


# In[6]:


device.Connect(serial)


# ### Quering device information

# In[18]:


deviceInfo = device.GetDeviceInfo()
print(f'deviceInfo.Name = {deviceInfo.Name}')
print(f'deviceInfo.SerialNumber = {deviceInfo.SerialNumber}')
print(f'deviceInfo.FirmwareVersion = {deviceInfo.FirmwareVersion}')
print(f'deviceInfo.DeviceType = {deviceInfo.DeviceType}')
print(f'deviceInfo.get_Description = {deviceInfo.get_Description()}')
print(f'deviceInfo.get_SoftwareVersion() = {deviceInfo.get_SoftwareVersion()}')


# ### Basic controls

# In[ ]:


# Enabling device
device.EnableDevice()


# In[8]:


# Disabling device
device.DisableDevice()


# In[9]:


# Identify device by blinking light on the front panel
device.IdentifyDevice()


# In[27]:


# ???
# returns boolean
device.get_CanHome()


# Returns if device enabled or not
device.IsEnabled


device.Position

---------------------------------------------------------------------------
DeviceSettingsException                   Traceback (most recent call last)
Input In [48], in <module>
----> 1 device.Position

DeviceSettingsException: Device settings not initialized
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.VerifyMotorSettings(Int32 functionDepth)
   at Thorlabs.MotionControl.GenericMotorCLI.AdvancedMotor.GenericAdvancedMotorCLI.get_Position()




```

**Comment by vstadnytskyi** [comment]
I tried to initilize via

```
device.InitializeGenericDevice()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [50], in <module>
----> 1 device.InitializeDevice()

TypeError: No method matches given arguments for InitializeDevice: ()
```

or 

```
device.InitializeGenericDevice()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Input In [49], in <module>
----> 1 device.InitializeGenericDevice()

TypeError: No method matches given arguments for InitializeGenericDevice: ()
```

**Comment by trautsned** [comment]
I recall the interface being cantankerous. I believe I had to call:
device.GetMotorConfiguration(serialNo)
I know it seems strange that getting a configuation is necessary, but I believe it was.

calling initialize_device should do it. Pass the device serial number as a string
initialize_device("45852301")

device = Thorlabs.MotionControl.IntegratedStepperMotorsCLI.LongTravelStage.CreateLongTravelStage("45852301")
device.Connect("45852301")
motorSettings  = device.GetMotorConfiguration("45852301")
print(motorSettings)

This is all from memory. Let me know if you are still having issues and I will fire up our system

**Comment by vstadnytskyi** [comment]
This is working initialization device function

```

import clr
clr.AddReference("System")

import sys
import time
import numpy as np
import matplotlib.pyplot as plt
import random  # only used for dummy data

from System import String
from System import Decimal
from System.Collections import *

# constants
sys.path.append(r"C:\Program Files\Thorlabs\Kinesis")
serial = '45252134'

clr.AddReference("Thorlabs.MotionControl.Controls")
import Thorlabs.MotionControl.Controls

clr.AddReference("Thorlabs.MotionControl.DeviceManagerCLI")
clr.AddReference("Thorlabs.MotionControl.GenericMotorCLI")
clr.AddReference("Thorlabs.MotionControl.IntegratedStepperMotorsCLI")
from Thorlabs.MotionControl.DeviceManagerCLI import *
from Thorlabs.MotionControl.GenericMotorCLI import *
from Thorlabs.MotionControl.IntegratedStepperMotorsCLI import *

POLLING_INTERVAL = 250
ENABLE_SLEEP_TIME = 0.1
INIT_TIMEOUT = 5000

def initialize_device(serial):
    from time import sleep
    # the request to build the device list is critical to operation of this code
    device_list_result = DeviceManagerCLI.BuildDeviceList()
    print(device_list_result)
    device = Thorlabs.MotionControl.IntegratedStepperMotorsCLI.LongTravelStage.CreateLongTravelStage(serial)
    device.Connect(serial)
    device.WaitForSettingsInitialized(INIT_TIMEOUT) #I think this is a crucial step in the initializatio
    device.EnableDevice()
    config = device.LoadMotorConfiguration(serial)
    deviceInfo = device.GetDeviceInfo()
    print(deviceInfo.Name, '  ', deviceInfo.SerialNumber)
    return device
```

**Comment by vstadnytskyi** [comment]
> I recall the interface being cantankerous. I believe I had to call: device.GetMotorConfiguration(serialNo) I know it seems strange that getting a configuation is necessary, but I believe it was.
> 
> calling initialize_device should do it. Pass the device serial number as a string initialize_device("45852301")
> 
> device = Thorlabs.MotionControl.IntegratedStepperMotorsCLI.LongTravelStage.CreateLongTravelStage("45852301") device.Connect("45852301") 
motorSettings = device.GetMotorConfiguration("45852301") 
print(motorSettings)
> 
> This is all from memory. Let me know if you are still having issues and I will fire up our system

I would get an error at this stage
`motorSettings = device.GetMotorConfiguration("45852301")`
